name: Deploy to GitHub Pages via angular-cli-ghpages

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Add Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install
      
    - name: Build Angular App
      run: npm run build
    
    - name: Deploy to gh pages
      run : |
        npx angular-cli-ghpages --dir=dist/proyecto-nombre --no-silent
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
