name: Deploy to GitHub Pages via angular-cli-ghpages

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Add Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install
      
    - name: Build Angular App
      run: npm run build:prod
    
    - name: Deploy to gh pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with: 
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: dist/proyecto-nombre
        enable_jekyll: true
